### Prototype build jobs ###
.build_script: &build_script
  - mkdir -p build/
  - cd build/
  - echo $CMAKE_CMD
  - $CMAKE_CMD
  - ninja

.test_script: &test_script
  - ctest -V

.build:
  variables:
    EXTRA_CMAKE_FLAGS: ""
  before_script:
    - export CMAKE_CMD="cmake -GNinja $EXTRA_CMAKE_FLAGS .."
  script:
    - *build_script

.build_and_test:
  extends: .build
  script:
    - *build_script
    - *test_script

### Tests ###
test:cpp14:debian:10:
  extends: .build_and_test
  needs: []
  image: volcart/vcbuilder-debian:10_v1.static
  variables:
    EXTRA_CMAKE_FLAGS: "-DOPENABF_BUILD_TESTS=ON"
  tags:
    - docker

test:cpp14:debian:11:
  extends: test:cpp14:debian:10
  image: ghcr.io/educelab/ci-docker:11_v2.static

test:cpp17:debian:10:
  extends: test:cpp14:debian:10
  variables:
    EXTRA_CMAKE_FLAGS: "-DOPENABF_BUILD_TESTS=ON -DCMAKE_CXX_STANDARD=17"

test:cpp17:debian:11:
  extends: test:cpp17:debian:10
  image: ghcr.io/educelab/ci-docker:11_v2.static

single_header_updated:
  needs: []
  image: python:3.11
  script:
    - python3 thirdparty/amalgamate/amalgamate.py -c single_include.json -s .
    - changed=$(git diff --stat)
    - if [[ "${changed}" != '' ]]; then echo "Files changed:" ${changed}; exit 1; fi
  tags:
    - docker

examples:debian:10:
  extends: .build
  needs: []
  image: volcart/vcbuilder-debian:10_v1.static
  variables:
    EXTRA_CMAKE_FLAGS: "-DOPENABF_BUILD_EXAMPLES=ON"
  tags:
    - docker

examples:debian:11:
  extends: .build
  needs: []
  image: ghcr.io/educelab/ci-docker:11_v2.static
  variables:
    EXTRA_CMAKE_FLAGS: "-DOPENABF_BUILD_EXAMPLES=ON"
  tags:
    - docker

### Docs ###
pages:
  needs: []
  image: debian:bullseye-backports
  before_script:
    - apt-get update
    - apt-get install -y build-essential doxygen graphviz texlive ghostscript cmake libeigen3-dev
  script:
    - mkdir -p build/
    - mkdir -p public/
    - cmake -S . -B build/ -DOPENABF_BUILD_DOCS=ON
    - cmake --build build/ --target docs
    - mv build/docs/html/ public/docs/
  artifacts:
    paths:
      - public
  tags:
    - docker
  only:
    - develop
